dist: trusty
sudo: required
language: node_js
node_js:
  - "node"
  - "9"
install:
  - npm i
script:
  - npm run build
  - npm run build:test:components
  - npm test
cache:
  directories:
    - "node_modules"
