dist: bionic
sudo: true
language: node_js
node_js:
  - "13"
  - "12"
  - "11"
  - "10"
  - "9"
install:
  - npm i
script:
  - npm run build
  - npm run build:test:components
  - npm test
cache:
  directories:
    - "node_modules"
