language: node_js
node_js:
  - "13"
  - "12"
  - "11"
  - "10"
  - "9"
  - "8"
  sudo: required
addons:
  chrome: stable
install:
  - npm i
script:
  - npm run build
  - npm run build:test:components
  - npm test
cache:
  directories:
    - "node_modules"